steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--production=false']

  # Build project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to GCS bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Remove existing files from bucket (force cache invalidation)
        echo "Force clearing bucket cache..."
        gsutil -m rm -r gs://webazul.pt/** || true

        # Copy build files to bucket
        echo "Listing files to upload:"
        find dist -type f -exec ls -la {} \;

        gsutil -m cp -r dist/* gs://webazul.pt/

        # Verify upload
        echo "Build completed at: $(date)"
        echo "Verifying uploads:"
        gsutil ls -la gs://webazul.pt/

        echo "Full index.html content:"
        gsutil cat gs://webazul.pt/index.html

        echo "Content verification:"
        gsutil cat gs://webazul.pt/index.html | wc -l
        gsutil cat gs://webazul.pt/index.html | grep -c "DOCTYPE\|html\|head\|body" || echo "HTML tags not found!"

        # Configure bucket for SPA (Single Page Application)
        gsutil web set -m index.html -e index.html gs://webazul.pt

        # Set proper cache headers
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.js
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.css
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.png
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.jpg
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.svg
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.ico
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webazul.pt/**/*.webp

        # Set short cache for index.html (5 minutes)
        gsutil -m setmeta -h "Cache-Control:public, max-age=300, s-maxage=300" gs://webazul.pt/index.html

        # Force immediate cache invalidation
        echo "Forcing cache invalidation..."
        gsutil -m setmeta -h "Cache-Control:no-cache, no-store, must-revalidate" gs://webazul.pt/index.html
        sleep 2
        gsutil -m setmeta -h "Cache-Control:public, max-age=300, s-maxage=300" gs://webazul.pt/index.html

# Timeout for the entire build process
timeout: '10m'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
